version: '3'


services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  scraper:
    build:
      context: ./scraper_app
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    restart: on-failure


  web:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
      - scraper

volumes:
  postgres_data:

